name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:     # manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: touhidcodes  

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -f output/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin output
